export const TODO_MOCKDATA = [
  {
    id: 1,
    title: "Buy groceries",
    description: "Milk, Bread, Eggs, Butter",
    due_date: "2024-07-26",
    priority: "high",
    completed: false,
  },
  {
    id: 2,
    title: "Finish project report",
    description: "Complete the final draft of the project report",
    due_date: "2024-07-30",
    priority: "medium",
    completed: false,
  },
  {
    id: 3,
    title: "Workout",
    description: "Go for a 30-minute run",
    due_date: "2024-07-25",
    priority: "low",
    completed: true,
  },
  {
    id: 4,
    title: "Read book",
    description: "Read 50 pages of 'The Great Gatsby'",
    due_date: "2024-07-27",
    priority: "medium",
    completed: false,
  },
  {
    id: 5,
    title: "Schedule dentist appointment",
    description: "Call the dentist to schedule an annual check-up",
    due_date: "2024-07-28",
    priority: "high",
    completed: false,
  },
  {
    id: 6,
    title: "Plan weekend trip",
    description: "Research and book accommodation for the weekend trip",
    due_date: "2024-08-01",
    priority: "medium",
    completed: false,
  },
  {
    id: 7,
    title: "Clean the house",
    description: "Vacuum, dust, and mop all rooms",
    due_date: "2024-07-29",
    priority: "low",
    completed: false,
  },
  {
    id: 8,
    title: "Pay utility bills",
    description: "Pay electricity and water bills online",
    due_date: "2024-07-27",
    priority: "high",
    completed: true,
  },
  {
    id: 9,
    title: "Attend team meeting",
    description: "Join the Zoom call for the weekly team meeting",
    due_date: "2024-07-26",
    priority: "medium",
    completed: true,
  },
  {
    id: 10,
    title: "Update resume",
    description: "Add recent work experience and skills to the resume",
    due_date: "2024-07-31",
    priority: "high",
    completed: false,
  },
];
